controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

products_list:
    path: /products
    controller: App\Controller\ProductController::getAllProducts
    methods: GET

product_selection:
    path: /products/{id}
    controller: App\Controller\ProductController::getProduct
    methods: GET

product_creation:
    path: /products
    controller: App\Controller\ProductController::createNewProduct
    methods: POST

product_deletion:
    path: /products/{id}
    controller: App\Controller\ProductController::deleteProduct
    methods: DELETE

product_modification:
    path: /products/{id}
    controller: App\Controller\ProduitController::alterProduct
    methods: PUT

login:
    path: /login
    controller: App\Controller\UsersController::login
    methods: POST
    controller: App\Controller\UsersController::login
    methods: POST

register:
    path: /register
    controller: App\Controller\UsersController::register
    methods: POST 


    # config/routes.yaml
panier_ajouter:
    path: /panier/ajouter
    controller: App\Controller\PanierController::ajouterProduit
    methods: POST

panier_supprimer:
    path: /panier/supprimer
    controller: App\Controller\PanierController::supprimerProduit
    methods: POST

panier_verifier:
    path: /panier/verifier
    controller: App\Controller\PanierController::verifierPanier
    methods: GET
